export const detailWrapper: string;
export const dockerImage: string;
export const error: string;
export const finish: string;
export const info: string;
export const running: string;
export const spanKey: string;
export const spanMark: string;
export const spanValue: string;
